### ISSUE TITLE
Remove .idea folder + add .gitignore file.

### ISSUE THREAD

**Issue by robertadriang** [teo000/PythonLabs#1]
Nu e o idee buna sa ai folderul .idea intr-un proiect. Folderul acela e strict pt preferinte/configs de PyCharm (deci ai putea avea coliziuni pe setari daca lucrati mai multi pe un workspace) si poate contine si sensitive data. (environment variables/locatie de SDK etc unde ai putea avea username/parole)
@teo000

**Comment by teo000** [comment]
Am rezolvat :)
